### ISSUE TITLE
Koala caused TFS build failures for ASPNET precompiled sites

### ISSUE THREAD

**Issue by bunceg** [stimpy77/FastKoala#41]
Not sure yet of the details of this - just had to spend the the time rolling back the changeset, however Koala worked just as expected on our local boxes but then the build broke on our locally hosted TFS build server with some very weird missing assembly errors. 

We think this is because we have the precompilation option enabled and, when the build tried to compile the site, as a config was missing with binding redirects, the assembly was not found (i.e. tfs build tried to find System.Web.Mvc 3.0.0.0 when it's a MVC 5.0 website)

This is just conjecture at the moment, but removing the koala change allowed the build to work again.

I will investigate further, but wanted to raise this as a heads up in case it's a known issue.

**Comment by stimpy77** [comment]
bunceg, I haven't heard of this issue, so I'm not sure what to think. Keep me posted if you find out more.

**Comment by bunceg** [comment]
Hi,
An update today is that the root cause of the issue is that the web.config is not being generated when we publish the site (e.g. right click on the project file and then publish the site). For example, if you use a "file system" publish, the output folder does not contain the web.config file. This missing web.config then means the binding redirects do not exist so the aspnet precompile falls over. Of course, this would also mean the site would fail to deploy correctly :(

This still fails to generate even if the web project file is in the root of the .sln file

I'm not quite sure how to work around this yet as performing a file based publish is pretty integral to our build process since it is a simple way to ensure the site is cleanly precompiled and only contains the files needed to run the site.

Anyway, hope this helps and any suggestions to workaround are welcome!

**Comment by stimpy77** [comment]
Which version of TFS, which version of Visual Studio, and which version of MSDeploy?

**Comment by bunceg** [comment]
I can get this to happen just using Visual Studio (2015) so it's unrelated to TFS as such. I'm not sure which version of MSDeploy VS2015 uses out of the box, but I have 7.1.1955 in my MS deploy folder under program files\iis\microsoft web deploy v3

The repro (for me) is to have a web app in VS, right click to get the properties, "publish", set this up to be a "file system" deployment, and then let it run. The output folder contains the deployed files but does not have a web.config

**Comment by stimpy77** [comment]
Reproduced. Fixed, will deploy soon. In the mean time, change the Build Action for the generated Web.config in the project manifest from None to Content.
