### ISSUE TITLE
Removing Fast Koala Changes

### ISSUE THREAD

**Issue by mjperna** [stimpy77/FastKoala#50]
How do you rollback the changes made by Fast Koala? I converted a web application over to use this tool, but I'd like to revert it back. Is there a process for achieving this result? What do you I have to change/update to get the normal web.config/transformation process back online?

**Comment by stimpy77** [comment]
You should have had a source control versioning system in place before you applied Fast Koala features to the project. That is the only automated way to back out.

Absent that, you will have to open the .csproj (or .vbproj?) project file in Notepad or ideally Notepad++ (or in Visual Studio right-click, Unload Project, then right-click, Edit), and edit the XML to remove the features that were added. Here's an overview of how to read the XML: [https://www.codementor.io/c_sharp/tutorial/quick-intro-to-msbuild-projects](https://www.codementor.io/c_sharp/tutorial/quick-intro-to-msbuild-projects)

The XML nodes you want to look for are primarily `<Target>` elements that invoke transformations. You might also create a new project of the same type (i.e. web app, or whatever type of project you have) and use BeyondCompare to compare the differences, ignoring the manifest files (`<Compile>` and `<None>` elements, etc).

**Comment by mjperna** [comment]
I got it figured out, thanks. We do have a source code control system; however, I wanted to give this a good chance to work for us. With a large team and three weeks worth of changes, rolling back was a lot more challenging than simply reverting things back manually. Overall, I think this is a nice tool, it just didn't quite work for us.

Thanks for the response.

**Comment by stimpy77** [comment]
Mmmm.. I check in at least daily, at least in a feature branch :) Would 
never let things accumulate for three weeks.

Sorry things didn't work for you. There are known showstoppers (such as 
FK falling apart if your projects are nested in solution folders, which 
is pretty normal). I just haven't had time to fix it and no one has 
picked up the ball (it's open source).

Cheers
