### ISSUE TITLE
Support for VS 2017

### ISSUE THREAD

**Issue by infomediadev** [stimpy77/FastKoala#55]
The current release 1.1.32 does not support Visual Studio 2017.
It would be very nice if this awesome tool 👍  could be upgraded to support VS2017.

**Comment by stimpy77** [comment]
Try https://github.com/stimpy77/FastKoala/releases/tag/fastkoala-unstable-v1.1.33-manual-vs2017

Experimental manual build. Thanks to @taylorjonl. I'll look at publishing this to the gallery as well.

**Comment by stimpy77** [comment]
Required a few add'l tweaks but I updated the binaries there.
https://visualstudiogallery.msdn.microsoft.com/d0c0559c-335a-4bdd-95d7-7782acdcd90b

**Comment by stimpy77** [comment]
Note that VS2017 will be a permanent branch until VS2015 has fully expired in relevance to the community (to the extent of Fast Koala support).
